name: "chris briones"
description: "A blog by Christian Briones."
safe: true
lsi: false
port: 3000

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
paginate: 10
permalink: /posts/:year/:month/:day/:title/

gems: [jekyll-paginate]

author:
  name: "Christian Briones"
  github: cwbriones
